### ISSUE TITLE
You should merge it with this one 

### ISSUE THREAD

**Issue by 2blackbar** [Leodotpy/sd-pixel#1]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-pixelization
 
![03223](https://user-images.githubusercontent.com/33694664/236649742-153352d4-175e-453f-bd71-e6f460e7a12e.png)

**Comment by Leodotpy** [comment]
Hi thanks for the suggestion. After consideration, I chose to keep mine seperate. This is mainly because my extension doesn't require any models to run. So I would like it to stay simple for new people to the scene to run.
