### ISSUE TITLE
Can You add bicubic as well next to nearneighbour?

### ISSUE THREAD

**Issue by 2blackbar** [Leodotpy/sd-pixel#3]
It can yield good results and more options would be nice.
Actually i tried it and Hamming is a better choice next to Lanczos which oversharpens a bit, so id keep the 3 - near,hamming,lanczos

**Comment by Leodotpy** [comment]
Hi. Thank you for your recommendation!
I have now added these features in commit [https://github.com/Leodotpy/sd-pixel/commit/19d845dc25310877585e3334b5a84e0317536c8c](https://github.com/Leodotpy/sd-pixel/commit/19d845dc25310877585e3334b5a84e0317536c8c)

sd-pixel now has support for Nearest Neighbor (default), Bicubic, Bilinear, Hamming, and Lanczos interpolation. 
Previews are shown [here](https://github.com/Leodotpy/sd-pixel#supported-downscaling-modes)
